[alias]
xtask = "run --package xtask --"
test-all = "run --package xtask -- test-all"
test-system = "run --package xtask -- test-system"
test-leaks = "run --package xtask -- test-leaks"
docs = "run --package xtask -- docs"
lint = "run --package xtask -- lint"
